spring.application.name=backend

server.port=8081
rest.base.url=http://localhost:8081
rest.user.name=admin
rest.user.password=admin

# Spring DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# Spring JPA
# Validation or export of schema DDL to the database (create, create-drop, validate, update, none)
spring.jpa.hibernate.ddl-auto=update
# Logging JPA Queries
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# Weekly project notifications
notifications.weekly.enabled=true
notifications.weekly.cron=0 0 9 ? * MON
notifications.weekly.zone=Europe/Warsaw
notifications.weekly.sender=no-reply@projekt.local
notifications.weekly.dry-run=true

#key-cloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/programowanie-zwinne

keycloak.server-url=http://localhost:8080
keycloak.realm=programowanie-zwinne
keycloak.admin-username=admin
keycloak.admin-password=admin
keycloak.client-id=admin-cli