spring.application.name=backend
spring.security.user.name=admin
spring.security.user.password=password123
spring.jpa.hibernate.ddl-auto=update

server.port=8081
rest.base.url=http://localhost:8080
rest.user.name=admin
rest.user.password=admin